{% set version = "3.0.0" %}

package:
  name: singularity
  version: {{ version }}

source:
  - folder: src/github.com/sylabs/singularity
    git_url: https://github.com/sylabs/singularity.git
    git_rev: v{{ version }}
    patches:
      - 0002-use-external-cni.diff

build:
  number: 1000
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('go') }} 1.11
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
  host:
    - pkg-config
    - libuuid
    - libarchive 3.3.*
    - libseccomp
    - openssl
  run:
    # CNI version from singularity/Gopkg.lock
    - cni-plugins >=0.7.4
    - libuuid
    - libarchive 3.3.*
    - libseccomp
    - openssl

test:
  commands:
    - which singularity
    - singularity --help

    # Ensure that built-in CNI is not installed
    - test ! -d $PREFIX/libexec/singularity/cni
    - test ! -d $PREFIX/etc/singularity/network

about:
  home: https://www.sylabs.io/singularity/
  license: BSD 3-Clause
  license_family: BSD
  license_file: src/github.com/sylabs/singularity/LICENSE-LBNL.md
  summary: "Singularity: Application containers for Linux"

  description: |
    Singularity is a container platform focused on supporting "Mobility of
    Compute"

    Mobility of Compute encapsulates the development to compute model where
    developers can work in an environment of their choosing and creation and
    when the developer needs additional compute resources, this environment
    can easily be copied and executed on other platforms. Additionally as the
    primary use case for Singularity is targeted towards computational
    portability, many of the barriers to entry of other container solutions do
    not apply to Singularity making it an ideal solution for users (both
    computational and non-computational) and HPC centers.

  dev_url: https://github.com/singularityware/singularity
  doc_url: https://www.sylabs.io/docs/

extra:
  recipe-maintainers:
    - bgruening
    - jakirkham
