travis:
  secure:
    BINSTAR_TOKEN: TfEnb8fnHIUzlB3Og6Q7hko7/hBsYzVujF1VIXhNNYbc82Ft0840RmidxwtI/WBZgfTt5C1tzUAHVCN2noADo1/PloAzh556KcLMGhY8TR6wgTpQGwXgNPQPVXFaWJOAc1yXzfX6FcqLQRSzJ28YzXiQShXhIn73+5crPuFMcWNBiEjP0QVwYklXjmvCdkICNmGZDK4az0H1EoEqHgq7OP8XJ/YMVQ5mMrqfsZtaF703/8Swd0OLG+K95dtECLEGoxTlz+/phCOvuK//mj5K8UQs2pQno3BmoGiYCJUim19xEelac8a0/zAZm7xEjgjRCswdvHLfNCcYQFVNNVmvuyGxLWup3g6JFhGi4dgXYRYUt95drmgBWQf73OyvH4cjYkPsGpMtB5WHpimuMrgLY7bd8ufS9ACTB4j0rZUkotBS+3/ev1qm77qTXdV2NSgepXO+uE7gOF2sRa47EzrAlWytjUX8Lz1r1M8wAgw5roHS0a/hrqxE1JQ0gnAlGzYQePuFpdHaOEE5eJeSswORV9M8LwwobaFMzoRkjv6wJ4MLtshtsduQT3t0qktzyzNj1/vfzHkeaEJB36MQE+z4AmQtpasw/XDwNTqJklOqMFJqqzr/UXxLrM7KZMakP5Ma1nmDFSrcmRuRXcL39wXHJCrhPdR71C5HBg84iG2q7GA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
